name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # 3.10 is the latest Python
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache for poetry, venv and deps
      id: cached-dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.local
          ~/.cache/pypoetry
          .venv
        key: cache-deps-${{ runner.os }}-${{ matrix.python-version }}-${{ hashfiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/lint.yml') }}
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.3.0
    - name: Install dependencies
      run: poetry install
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
    - name: Pylint and Pycodestyle
      run: |
        poetry run pylint pytamaro
        poetry run pycodestyle .
